name: Build the project

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-medium

    - run: DISM.exe /Online /Add-Capability /CapabilityName:Language.Fonts.Hans~~~und-HANS~0.0.1.0
    - run: DISM.exe /Online /Add-Capability /CapabilityName:Language.Fonts.Hant~~~und-HANT~0.0.1.0
    - run: latexmk -pdf -pdflatex=xelatex main.tex
    - run: biber main
    - run: latexmk -f -pdf -pdflatex=xelatex -interaction=nonstopmode main.tex
    - run: latexmk -c
    
    - uses: actions/upload-artifact@v3
      with:
        name: thesis pdf
        path: main.pdf